# Generated by Django 5.0.3 on 2024-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PE', 'در انتظار تایید'), ('PU', 'تائید شده'), ('RE', 'رد شده'), ('SP', 'هرزنامه')], default='PE', max_length=2),
        ),
    ]
